### ISSUE TITLE
Get fucked retard

### ISSUE THREAD

**Issue by SWP360** [Itroublve/Token-Browser-Password-Stealer-Creator#1]
Lmao you really tried to token log me and ended up getting token logged. Say goodbye buddy

**Comment by Itroublve** [comment]
Are you a retard?
1) I don't even know you
2) Where is the proof
3) Like, dude. I haven't got token logged in a while lmao.
So gg, fkn liar 💯

**Comment by lasagnaaf** [comment]
> Lmao you really tried to token log me and ended up getting token logged. Say goodbye buddy

is his token logger here on github trying to log US?

**Comment by Itroublve** [comment]
What do u think? The source is on GitHub, find the stealer.
