### ISSUE TITLE
Multiple questions.

### ISSUE THREAD

**Issue by RyZe-Misty** [Itroublve/Token-Browser-Password-Stealer-Creator#10]
What .net frameworks is needed to build the stealer.

Also for the sendhookfile.exe and tokenstealer.bat section in the builder, do we put the file paths?

**Comment by Itroublve** [comment]
.NET Framework for Developers, and latest version is recommended, also. For the files, you get their "direct-download-link"... A link which will make the file download instantly on click without opening any new tab or anything.
