### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by Bruno963max** [Itroublve/Token-Browser-Password-Stealer-Creator#11]
I must put the webhook is where is which file to make in executable?

**Comment by NowaX-ctrl** [comment]
Hello, can you send extra link for the Token Stealer.bat and Sendhookfile.exe? If i download your "project" they arent in there. Cna you make them extra maybe?? Btw. Awesome Job mate, im a fan of your work!

**Comment by Itroublve** [comment]
> Hello, can you send extra link for the Token Stealer.bat and Sendhookfile.exe? If i download your "project" they arent in there. Cna you make them extra maybe?? Btw. Awesome Job mate, im a fan of your work!

Hello, sorry. They are created automatically. Also, the Sendhookfile.exe source can be found in the folder named "GetToken". For the Token Stealer.bat you can just view TokenStealer.bin given in release. I'll remove the requirement for it in V6 :)

**Comment by NowaX-ctrl** [comment]
hey mate,
your really the best : ) ❤️❤️
Thanks for the response: )
I follow you also on Instagram and Twitter : )
🤝🤝🤝🤝🤝🤝🤝🤝
