### ISSUE TITLE
Where does the exe or the file that I creadet go??

### ISSUE THREAD

**Issue by Theo789123** [Itroublve/Token-Browser-Password-Stealer-Creator#17]
Where does the created file go I mean the exe?? I cant find it

**Comment by Itroublve** [comment]
The created stealer is automatically saved in the same folder as where the creator is... The stealer files is saved in "./output". Also, try disabling antivirus as that might delete the exe.

btw, sorry for late resp. Let me know with screenshots or more details on what you doing. 

Regards.
