### ISSUE TITLE
Great Software!

### ISSUE THREAD

**Issue by skidbyte** [Itroublve/Token-Browser-Password-Stealer-Creator#18]
Sorry im writing this as an Issue, im not quite sure how to comment on repositories.
This thing works like a charm and has no issues.
I was wondering if you could add a small function that shows if the logged token has billing info connected? I think you can just rip the code from a basic token logger as you will find them all over the place. For example on github you can find DreadBreads raid toolbox which has a built in tokenstealer builder. You can just skid the code that checks if the account has billing info and put it into your software.
Have a great day and keep updating!

**Comment by Itroublve** [comment]
Eh, it's really easy... I already have it in my bot, I'm working on ItroublveTSC V6 right now, and that'll have that for sure. Thanks for your feedback. 

Regards.
