### ISSUE TITLE
I hope this will only be used for educational purposes and not to harm anyone or threat anyone!

### ISSUE THREAD

**Issue by 0xLyptox** [Itroublve/Token-Browser-Password-Stealer-Creator#3]
![image](https://user-images.githubusercontent.com/51520651/97789967-ff8e7c00-1bc4-11eb-9242-4535aeb7791b.png)
Yes, of course. I would never do this. Hopefully you won't going against your own hopes ;)

**Comment by v0nya** [comment]
uhm, yeah

**Comment by MCAki06** [comment]
no, he hacking peoples in discord using this library.
![image](https://user-images.githubusercontent.com/58387441/99078015-f71f4380-25bd-11eb-99e9-346156f1d690.png)
decompiled code of sent mega link:
https://i.gyazo.com/thumb/1200/6ea33e228ec664d9c450a377026f2d05-png.jpg

**Comment by Itroublve** [comment]
> no, he hacking peoples in discord using this library.
> ![image](https://user-images.githubusercontent.com/58387441/99078015-f71f4380-25bd-11eb-99e9-346156f1d690.png)
> decompiled code of sent mega link:
> https://i.gyazo.com/thumb/1200/6ea33e228ec664d9c450a377026f2d05-png.jpg

You see it's public, and that Discord account isn't even mine. Neither do I speak that language.
I've got no use of tokens or passwords as that's not even useful, it's just skiddos like NinjaH4X and iLinked...

**Comment by Itroublve** [comment]
I've put everything required on GitHub as you can see the changes which I make, so if I would put a stealer or anything it would be pretty obvious by looking at this here.
