### ISSUE TITLE
Cant use at all.

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [Itroublve/Token-Browser-Password-Stealer-Creator#4]
![image](https://user-images.githubusercontent.com/75588579/101300299-c0260180-37fa-11eb-861a-3ca529f6dcef.png)

**Comment by Itroublve** [comment]
https://www.youtube.com/watch?v=Y-RypyG2bcE, Watch this tutorial on usage.. Probably will help you using this.
