### ISSUE TITLE
?

### ISSUE THREAD

**Issue by leoOze** [Itroublve/Token-Browser-Password-Stealer-Creator#6]
![image](https://user-images.githubusercontent.com/52644327/101586151-09737e00-39c0-11eb-8dca-4446a2dff3b7.png)
some1 is using this thing to make bad things

**Comment by 7wr** [comment]
if you dont want him mading these things delete his webhook every time posting a delete request

**Comment by Itroublve** [comment]
Mhm, well I can't really stop this from happening. All you could do it delete his webhook and hope he gives up... Or just send the link to where he uploads it and I will delete his webhook everytime.
