### ISSUE TITLE
[FEATURE] Discord Development

### ISSUE THREAD

**Issue by k6d** [Itroublve/Token-Browser-Password-Stealer-Creator#8]
Adding Discord development version could be good cause some people use it 

Download: https://discordapp.com/api/download/development?platform=win

**Comment by Itroublve** [comment]
Sorry for late response, but sure I can add it.

**Comment by Itroublve** [comment]
I couldn't find anyway to "inject" into the Discord Development version, although I've added the path to get token to the stealer for V6 release.
