### ISSUE TITLE
I can’t open the app

### ISSUE THREAD

**Issue by zDrillah** [Itroublve/Token-Browser-Password-Stealer-Creator#9]
Hey men,i can't open the app because all the things are on .cs,can you help me sending a video of how i can open?

**Comment by Itroublve** [comment]
It's the source, if you want you can go to releases and download or to our website "https://itroublvehacker.ml" (ad-alert)

**Comment by zDrillah** [comment]
> It's the source, if you want you can go to releases and download or to our website "https://itroublvehacker.ml" (ad-alert)

Ok tysm
